config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  resources :profs
  devise_for :users
  resources :directions do
    resources :profs
  end

   root 'welcome#index'

  get 'persons/profile', as: 'user_root'

  get 'dir' => 'directions#index'

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  has_many :profs
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  #before_filter :authenticate_user!, :except => [:edit, :update, :destroy]

  before_action :set_direction, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  # GET /directions
  # GET /directions.json
  def index
    @directions = Direction.all
  end

  # GET /directions/1
  # GET /directions/1.json
  def show
  end

  # GET /directions/new
  def new
    @direction = Direction.new
  end

  # GET /directions/1/edit
  def edit
    #authorize! :update, @direction
  end

  # POST /directions
  # POST /directions.json
  def create

    @direction = Direction.new(direction_params)

    respond_to do |format|
      if @direction.save
        format.html { redirect_to @direction, notice: 'Direction was successfully created.' }
        format.json { render :show, status: :created, location: @direction }
      else
        format.html { render :new }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directions/1
  # PATCH/PUT /directions/1.json
  def update
    respond_to do |format|
      if @direction.update(direction_params)
        format.html { redirect_to @direction, notice: 'Direction was successfully updated.' }
        format.json { render :show, status: :ok, location: @direction }
      else
        format.html { render :edit }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directions/1
  # DELETE /directions/1.json
  def destroy
    @direction.destroy
    respond_to do |format|
      format.html { redirect_to directions_url, notice: 'Direction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direction
      @direction = Direction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direction_params
      params.require(:direction).permit(:name, :descr)
    end
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/views/directions/_form.html.erb
<%= form_for(@direction) do |f| %>
  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %> prohibited this direction from being saved:</h2>

      <ul>
      <% @direction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descr %><br>
    <%= f.text_field :descr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directions/edit.html.erb
<h1>Editing Direction</h1>

<%= render 'form' %>

<%= link_to 'Show', @direction %> |
<%= link_to 'Back', directions_path %>

app/views/directions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <center><h1>Направления</h1></center>
  <% if can? :create, @direction %>
    <%= link_to 'Создать', new_direction_path %>
  <% end %>

    <br>
  <% @directions.each do |direction| %>
    <div class="content">
      <%= link_to direction.name, direction %>
      <% if can? :update, @direction %>
        <td><%= link_to 'Edit', edit_direction_path(direction) %></td>
      <% end %>
      <% if can? :destroy, @direction %>
        <td><%= link_to 'Destroy', direction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </div>
  <% end %>
</div>

app/views/directions/new.html.erb
<h1>New Direction</h1>

<%= render 'form' %>

<%= link_to 'Back', directions_path %>

app/views/directions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<center><h1>Направление <%= @direction.name %></h1></center>
  <br>
<% @direction.profs.each do |prof| %>
    <div class="content">
    </p><%= prof.name %>
        </div>
<% end %>

  <% if can? :create, @prof %>
<h2>Добавить профессию:</h2>
<%= form_for([@direction, @direction.profs.build]) do |f| %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :desc %><br>
        <%= f.text_area :desc %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
<% end %>
    </div>
<% end %>