config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  resources :profs
  devise_for :users
  resources :directions do
    resources :profs
  end

   root 'welcome#index'

  get 'persons/profile', as: 'user_root'

  get 'dir' => 'directions#index'

end

app/models/prof.rb
class Prof < ActiveRecord::Base
  belongs_to :direction
end

app/controllers/profs_controller.rb
class ProfsController < ApplicationController
  before_action :set_prof, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /profs
  # GET /profs.json
  def index
    @profs = Prof.all
  end

  # GET /profs/1
  # GET /profs/1.json
  def show
  end

  # GET /profs/new
  def new
    @prof = Prof.new
  end

  # GET /profs/1/edit
  def edit
  end


  # POST /profs
  # POST /profs.json
  def create
    if !@direction
      @prof = Prof.new(prof_params)
    else
    @direction = Direction.find(params[:direction_id])
    @prof = @direction.profs.create(prof_params)
    end

    respond_to do |format|
      if @prof.save
        format.html { redirect_to @prof, notice: 'Prof was successfully created.' }
        format.json { render :show, status: :created, location: @prof }
      else
        format.html { render :new }
        format.json { render json: @prof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profs/1
  # PATCH/PUT /profs/1.json
  def update
    respond_to do |format|
      if @prof.update(prof_params)
        format.html { redirect_to @prof, notice: 'Prof was successfully updated.' }
        format.json { render :show, status: :ok, location: @prof }
      else
        format.html { render :edit }
        format.json { render json: @prof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profs/1
  # DELETE /profs/1.json
  def destroy
    @prof.destroy
    respond_to do |format|
      format.html { redirect_to profs_url, notice: 'Prof was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prof
      @prof = Prof.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prof_params
      params.require(:prof).permit(:name, :desc, :direction_id)
    end
end

app/helpers/profs_helper.rb
module ProfsHelper
end

app/views/profs/_form.html.erb
<%= form_for(@prof) do |f| %>
  <% if @prof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prof.errors.count, "error") %> prohibited this prof from being saved:</h2>

      <ul>
      <% @prof.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :direction_id %><br>
    <%= f.text_field :direction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profs/edit.html.erb
<h1>Editing Prof</h1>

<%= render 'form' %>

<%= link_to 'Show', @prof %> |
<%= link_to 'Back', profs_path %>

app/views/profs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <center><h1>Профессии</h1></center>
  <% if can? :create, @prof %>
      <%= link_to 'Создать', new_prof_path %>
  <% end %>

  <br>
  <% @profs.each do |prof| %>
      <div class="content">
        <%= link_to prof.name, prof %>
        <% if can? :update, @prof %>
            <td><%= link_to 'Edit', edit_prof_path(prof) %></td>
        <% end %>
        <% if can? :destroy, @prof %>
            <td><%= link_to 'Destroy', prof, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </div>
  <% end %>
</div>

app/views/profs/new.html.erb
<h1>New Prof</h1>

<%= render 'form' %>

<%= link_to 'Back', profs_path %>

app/views/profs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prof.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @prof.desc %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @prof.direction %>
</p>

<%= link_to 'Edit', edit_prof_path(@prof) %> |
<%= link_to 'Back', profs_path %>